spring:
  application:
    name: dividend
  security:
    oauth2:
      resourceserver:



  h2:
    console:
      path: /h2-console
      enabled: 'true'

  jpa:
    defer-datasource-initialization: 'true'
    hibernate:
      ddl-auto: create
    show-sql: 'true'


  datasource:
    password: ''
    driver-class-name: org.h2.Driver
    username: sa
    url: jdbc:h2:mem:dayone;DB_CLOSE_DELAY=-1


  data:
    redis:
      port: '6379'
      host: localhost


  scheduler:
  scrap:
    yahoo: 0 0/5 * * * *



  jwt:
    secret: ZGF5b25lLXNwcmluZy1ib290LWRpdmlkZW5kLXByb2plY3QtdHV0b3JpYWwtand0LXNlY3JldC1r

  